name:                member-manager
version:             0.1.0.0
github:              "stroebel/member-manager"
license:             BSD3
author:              "Jaco Stroebel"
maintainer:          "str.jac@gmail.com"
copyright:           "2018 Jaco Stroebel"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/member-manager#readme>

dependencies:
- base >= 4.7 && < 5
- text >= 1.2 && < 1.3

extra-deps:
- safe-money-0.4.1

library:
  source-dirs: src

executables:
  member-manager-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - member-manager

tests:
  member-manager-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - member-manager
